//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _05.StringContainer.StringContainCounter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StringContainCounter.IServiceStringContainer")]
    public interface IServiceStringContainer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStringContainer/PrintContainCount", ReplyAction="http://tempuri.org/IServiceStringContainer/PrintContainCountResponse")]
        string PrintContainCount(string part, string container);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStringContainer/PrintContainCount", ReplyAction="http://tempuri.org/IServiceStringContainer/PrintContainCountResponse")]
        System.Threading.Tasks.Task<string> PrintContainCountAsync(string part, string container);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceStringContainerChannel : _05.StringContainer.StringContainCounter.IServiceStringContainer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceStringContainerClient : System.ServiceModel.ClientBase<_05.StringContainer.StringContainCounter.IServiceStringContainer>, _05.StringContainer.StringContainCounter.IServiceStringContainer {
        
        public ServiceStringContainerClient() {
        }
        
        public ServiceStringContainerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceStringContainerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStringContainerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStringContainerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PrintContainCount(string part, string container) {
            return base.Channel.PrintContainCount(part, container);
        }
        
        public System.Threading.Tasks.Task<string> PrintContainCountAsync(string part, string container) {
            return base.Channel.PrintContainCountAsync(part, container);
        }
    }
}
