//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02.DayOfWeekServiceConsoleApplication.ServiceDayGetterConsoleApp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDayGetterConsoleApp.IServiceDayGetter")]
    public interface IServiceDayGetter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDayGetter/GetDay", ReplyAction="http://tempuri.org/IServiceDayGetter/GetDayResponse")]
        string GetDay(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDayGetter/GetDay", ReplyAction="http://tempuri.org/IServiceDayGetter/GetDayResponse")]
        System.Threading.Tasks.Task<string> GetDayAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDayGetterChannel : _02.DayOfWeekServiceConsoleApplication.ServiceDayGetterConsoleApp.IServiceDayGetter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDayGetterClient : System.ServiceModel.ClientBase<_02.DayOfWeekServiceConsoleApplication.ServiceDayGetterConsoleApp.IServiceDayGetter>, _02.DayOfWeekServiceConsoleApplication.ServiceDayGetterConsoleApp.IServiceDayGetter {
        
        public ServiceDayGetterClient() {
        }
        
        public ServiceDayGetterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDayGetterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDayGetterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDayGetterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDay(System.DateTime date) {
            return base.Channel.GetDay(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayAsync(System.DateTime date) {
            return base.Channel.GetDayAsync(date);
        }
    }
}
