#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using MySQL.Models.OpenAccess;

namespace MySQL.Models.OpenAccess	
{
	public partial class Product
	{
		private int productID;
		public virtual int ProductID
		{
			get
			{
				return this.productID;
			}
			set
			{
				this.productID = value;
			}
		}
		
		private int vendorID;
		public virtual int VendorID
		{
			get
			{
				return this.vendorID;
			}
			set
			{
				this.vendorID = value;
			}
		}
		
		private string productName;
		public virtual string ProductName
		{
			get
			{
				return this.productName;
			}
			set
			{
				this.productName = value;
			}
		}
		
		private int measureID;
		public virtual int MeasureID
		{
			get
			{
				return this.measureID;
			}
			set
			{
				this.measureID = value;
			}
		}
		
		private decimal basePrice;
		public virtual decimal BasePrice
		{
			get
			{
				return this.basePrice;
			}
			set
			{
				this.basePrice = value;
			}
		}
		
		private Vendor vendor;
		public virtual Vendor Vendor
		{
			get
			{
				return this.vendor;
			}
			set
			{
				this.vendor = value;
			}
		}
		
		private Measure measure;
		public virtual Measure Measure
		{
			get
			{
				return this.measure;
			}
			set
			{
				this.measure = value;
			}
		}
		
	}
}
#pragma warning restore 1591
