//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLite.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public long ReportID { get; set; }
        public string VendorName { get; set; }
        public int TotalQuantitySold { get; set; }
        public decimal TotalIncome { get; set; }
        public string ProductName { get; set; }
    }
}
