//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studio
    {
        public Studio()
        {
            this.Movies = new HashSet<Movy>();
        }
    
        public int StudioId { get; set; }
        public string StudioName { get; set; }
        public string StudioAddress { get; set; }
    
        public virtual ICollection<Movy> Movies { get; set; }
    }
}
